### ISSUE TITLE
boulder: Consider adding a separate `fetch` phase

### ISSUE THREAD

**Issue by ermo** [serpent-os/moss#264]
Modern languages typically come with their own package managers.

To make it possible to fetch external modules per a controlled set of dependencies, perhaps it would make sense to offer an extra `fetch` phase where networking is implicitly allowed, whilst then turning off networking for all remaining phases?

This might look like the following

```YAML
# (...)
networking: no
fetch: |
    %cargo_fetch # or %go_get or (...)
# no setup phase necessary here
build: |
   %cargo_build
install: |
    %cargo_install
```
