### ISSUE TITLE
moss: Add the ability to deprecate and replace recipes/.stones

### ISSUE THREAD

**Issue by ermo** [serpent-os/moss#318]
It is currently possible to install `golang-1.20.3` and `golang-devel-1.20` next to each other, because `golang-devel` is still in the volatile repository.

This needs a solution.

**Comment by ikeycode** [comment]
The current thoughts for *replaces* would be to rely on abusing the providers system, such that a yaml could do the following..


```yaml
packages:
    - "%(name)":
        provides:
            - name(golang-devel)
```

Worth pointing out that "obsoletes" is invariably a hint in an indexing mechanism to occlude a name from emission, so would appear to be a vessel problem.
