### ISSUE TITLE
boulder: profiles does not inherit from root key where profile is empty

### ISSUE THREAD

**Issue by joebonrichie** [serpent-os/moss#338]
See https://github.com/serpent-os/recipes/pull/244 as an example

e.g.
```yaml
emul32      : yes
profiles    :
    - emul32:
        setup: |
            do emul32 specific thing
setup       : |
    do thing
build       : |
    build
install     : |
    install
```

the emul32 phases for build and install do not get executed here, only profile; due to the addition of the emul32 specific setup phase.
